### ISSUE TITLE
Change format of git tags so the library is go module aware

### ISSUE THREAD

**Issue by m90** [line/line-bot-sdk-go#101]
If you currently install the package in a Go 1.11 module aware environment, the existing git tags will be ignored as they are expected to start with a `v`, i.e. `3.0.0` should be `v3.0.0` instead: https://github.com/golang/go/wiki/Modules#modules

Is it possible to start tagging the releases in this way, so that it can be properly consumed as a module as well?

**Comment by suzuki-shunsuke** [comment]
Thank you for the issue!
I have created tags started with "v".
https://github.com/line/line-bot-sdk-go/tags

And we will created tags started with "v" from the next time.

Thank you again.

**Comment by m90** [comment]
Thanks, I'm already consuming the tagged version!
