### ISSUE TITLE
Event struct will not be able to Unmarshal again.

### ISSUE THREAD

**Issue by k2wanko** [line/line-bot-sdk-go#14]
MarshalJSON has not been implemented in the Event struct.

```
cannot unmarshal string into Go value of type int64
```

**Comment by sugyan** [comment]
Why do you need to marshal event structs?

**Comment by k2wanko** [comment]
I want to serialize in order to put the Event struct to Queue.

**Comment by mokejp** [comment]
Thanks for reporting.
It supported now.

**Comment by k2wanko** [comment]
Thank you 👍
