### ISSUE TITLE
proposal: Support for AppEngine

### ISSUE THREAD

**Issue by k2wanko** [line/line-bot-sdk-go#15]
Please support urlfetch.

FYI: https://godoc.org/google.golang.org/appengine/urlfetch

Like this

```go
var bot *linebot.Client

func init() {
	bot = linebot.New(
		os.Getenv("LINE_BOT_CHANNEL_SECRET"),
		os.Getenv("LINE_BOT_CHANNEL_TOKEN"))
}

func handle(w http.ResponseWriter, r *http.Request) {
	ctx := appengine.NewContext(r)
	...
	if _, err = bot.PushMessage(...).Context(ctx).Do(); err != nil {
		log.Errorf(ctx, "Push Message error: %v", err)
	}
}
```

**Comment by mokejp** [comment]
You can use urlfetch if you initialize `linebot.Client` for each context.

I present a sample.
https://github.com/mokejp/line-bot-sdk-go/blob/example-gae/examples/echo_bot_gae/server.go

**Comment by mokejp** [comment]
This SDK should can be used on appengine. 

But we think It should not depend on the particular platform because that confuses the people who use other platform.

If you have a idea that is not depends on the platform, we welcome your p-r.

Thank you.
