### ISSUE TITLE
Update issue.md

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-go#155]
As the LINE Platform feedback repository(https://github.com/line/line-platform-feedback) has been archived, we need to update issue.md accordingly

**Comment by nasa9084** [comment]
fixed https://github.com/line/line-bot-sdk-go/commit/9f774b69d7a0fa4d6143b2ac4a8ac9dbc3809da9

**Comment by tkgauri** [comment]
@nasa9084 Thank you 👍
