### ISSUE TITLE
Unexpect callback information on Operation message

### ISSUE THREAD

**Issue by kkdai** [line/line-bot-sdk-go#2]
Because I use Line-Go-Bot SDK, so I file issue here.

I find the Line Server is not provide expect callback for operation (expecially on `opType=4` (Added as friend))

When I try to get `opType` message on JSON, I get as follow:

```
{
  "result": [
    {
      "content": {
        "params": [
          "XXX",
          null,
          null
        ],
        "message": null,
        "reqSeq": 0,
        "revision": 932,
        "opType": 4
      },
      "createdTime": 1462860363348,
      "eventType": "138311609100106403",
      "from": "XXX",
      "fromChannel": 1341301815,
      "id": "SOME_ID",
      "to": [
        "MSGID"
      ],
      "toChannel": 1462189304
    }
  ]
}
```

It missing some data under `content` so I cannot get any `From` information  by using `result.Content()` also `content.OperationContent()`.

Here is example from Line [Document](https://developers.line.me/bot-api/api-reference#receiving_operations).

```
{"result":[
  {
    "from":"u2ddf2eb3c959e561f6c9fa2ea732e7eb8",
    "fromChannel":1341301815,
    "to":["u0cc15697597f61dd8b01cea8b027050e"],
    "toChannel":1441301333,
    "eventType":"138311609000106303",
    "id":"ABCDEF-12345678901",
    "content": {
      "location":null,
      "id":"325708",
      "contentType":1,
      "from":"uff2aec188e58752ee1fb0f9507c6529a",
      "createdTime":1332394961610,
      "to":["u0a556cffd4da0dd89c94fb36e36e1cdc"],
      "toType":1,
      "contentMetadata":null,
      "text":"Hello, BOT API Server!"
    }
  },
  ...
]}
```

What I should expect is `from` , `id`, `to` under `content` but we could not get from Line Server callback.

The only way I get user information from Operation Callback is `result.RawContent.Params[0]` and I don't think it is expected by document.

Please let me know if you need any more detail.

**Comment by sugyan** [comment]
It's fixed by v2 release
