### ISSUE TITLE
Support icon-nickname-switch

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-go#204]
News: https://developers.line.biz/en/news/2020/03/17/icon-nickname-switch/
Doc: https://developers.line.biz/en/docs/messaging-api/icon-nickname-switch/

**Comment by kkdai** [comment]
Hi @tkgauri 
This issue has been fixed by https://github.com/line/line-bot-sdk-go/commit/aef348d3e88f13076925ad11c0891e20d8bc915e
