### ISSUE TITLE
Consider to support API call without access-token

### ISSUE THREAD

**Issue by kogai** [line/line-bot-sdk-go#219]
Let me check how to use the Message API to get a short live access token 🙏 

According to [the documentation](https://developers.line.biz/en/reference/messaging-api/#issue-channel-access-token),
It isn't necessary Authorization header to issue an access token.

Nevertheless, to instantiate `Client` for enable to call `IssueAccessTokenV2` method requires an access token itself 🤔 

Fortunately, in a case of me, thanks to exposing APIEndpointBase and APIEndpointIssueAccessToken,
It was easy to issue an appropriate request by using `http` module of std-lib.

By the way, If any function or structure which supports some interface that does not require an access token might be nice.

Thanks for reading.

**Comment by Yang-33** [comment]
https://github.com/line/line-bot-sdk-go/pull/392 supports this!
