### ISSUE TITLE
The endpoint to get statistics is now available in Indonesia (ID)

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-go#224]
News: https://developers.line.biz/en/news/2020/08/05/endpoint-to-get-statistics-is-now-available-in-Indonesia/
Doc: https://developers.line.biz/en/reference/messaging-api/#get-demographic

**Comment by kkdai** [comment]
This should already completed by ffbe5cb9b5ac8145dbd012951b15f905aabe85ec
