### ISSUE TITLE
Support Flex Message Update 2

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-go#234]
News: https://developers.line.biz/en/news/2020/10/08/flex-message-update-2-released/

1. - [ ] [Changed the maximum number of bubbles that can be included in a carousel](https://developers.line.biz/en/reference/messaging-api/#f-carousel)
2. - [x] [Box component has justifyContent and alignItems property](https://developers.line.biz/en/reference/messaging-api/#box)
3. - [x] [Use linear gradient as the background image for a box component by setting its background.type property equal to linearGradient.](https://developers.line.biz/en/reference/messaging-api/#box)
4. - [ ] [Allowed an empty array to be specified as the value of a box's contents property](https://developers.line.biz/en/reference/messaging-api/#box)
5. - [x] [Added support for animated images](https://developers.line.biz/en/reference/messaging-api/#f-image)
6. - [ ] [Changed how sizes are specified](https://developers.line.biz/en/news/2020/10/08/flex-message-update-2-released/#update-size)
	1. - [ ] [Image component](https://developers.line.biz/en/docs/messaging-api/flex-message-layout/#image-size)
	2. - [x] [Icon, text, and span components](https://developers.line.biz/en/docs/messaging-api/flex-message-layout/#other-component-size) 
7. - [x] [Allowed text to automatically shrink to fit a component's width](https://developers.line.biz/en/news/2020/10/08/flex-message-update-2-released/#update-adjust-mode) - [Text](https://developers.line.biz/en/reference/messaging-api/#f-text) and [Button](https://developers.line.biz/en/reference/messaging-api/#button)
8. - [x] [Spacer has been discontinued](https://developers.line.biz/en/news/2020/10/08/flex-message-update-2-released/#update-spacer)

**Comment by tokuhirom** [comment]
@kkdai, which checkboxes are not implemented yet? Have you implemented all the features? If so, close the Issue.

**Comment by kkdai** [comment]
@tokuhirom  Thank you for reminding me, I will review the current status and check with PR #253

**Comment by kkdai** [comment]
2, 5, 7 are fixed by #253

**Comment by kkdai** [comment]
Hi @hinoguma,
Is it possible to help on items 1, 3, 4, and 6?
I will help you to review, thank you.

**Comment by kkdai** [comment]
item 8 has been completed.

**Comment by hinoguma** [comment]
@kkdai 

> Is it possible to help on items 1, 3, 4, and 6?
OK!
I'll do them as soon as I can, but might take a few days.

**Comment by hinoguma** [comment]
@kkdai 
we don't need to do anything below.
I think we can put a check mark.

1, Changed the maximum number of bubbles that can be included in a carousel
Mx number validation is sdk-user's responsibility.
This sdk do not validate maximum number of template message actions and so on.

4, Allowed an empty array to be specified as the value of a box's contents property
We've tested this case yet.
https://github.com/line/line-bot-sdk-go/blob/32445b0c970dfbc668213212c355b7813c00e70f/linebot/flex_test.go#L613-L679

6, Changed how sizes are specified
　Image component

`type FlexImageSizeType string` exists.

**Comment by kkdai** [comment]
#269 for 3

**Comment by kkdai** [comment]
> @kkdai
> we don't need to do anything below.
> I think we can put a check mark.
> 
> 1, Changed the maximum number of bubbles that can be included in a carousel
> Mx number validation is sdk-user's responsibility.
> This sdk do not validate maximum number of template message actions and so on.
> 
> 4, Allowed an empty array to be specified as the value of a box's contents property
> We've tested this case yet.
> https://github.com/line/line-bot-sdk-go/blob/32445b0c970dfbc668213212c355b7813c00e70f/linebot/flex_test.go#L613-L679
> 
> 6, Changed how sizes are specified
> 　Image component
> 
> `type FlexImageSizeType string` exists.

Confirmed  1, 4, 6 fixed already. Mark this issue as close.
Thank you @hinoguma
