### ISSUE TITLE
Please make thumbnail image optional with NewButtonsTemplate method.

### ISSUE THREAD

**Issue by tomyhero** [line/line-bot-sdk-go#24]
Hi. I want to use NewButtonsTemplate() without thumbnail. I heard other language SDK support without thumbnail.  Can you support?  Thank you!

```
APIError 400 A message (messages[0]) in the request body is invalid
[template[@type=buttons].thumbnailImageUrl] must be non-empty text
[template[@type=buttons].thumbnailImageUrl] invalid uri scheme
```

**Comment by sugyan** [comment]
Thanks for reporting. This SDK couldn't send buttons template messages without thumbnail image URL by our mistake. It was fixed by #25 .
Please try again with the latest version.
