### ISSUE TITLE
How to use PushMessage with event.Source.UserID

### ISSUE THREAD

**Issue by appleboy** [line/line-bot-sdk-go#32]
Hi,

I can get the `event.Source.UserID` from [this example](https://github.com/line/line-bot-sdk-go/blob/master/examples/echo_bot/server.go) but got the following message using `PushMessage` func.

```go
if _, err = bot.PushMessage(event.Source.UserID, linebot.NewTextMessage(message.Text)).Do(); err != nil {
  log.Print(err)
}
```

Error Message: `linebot: APIError 403 Access to this API is not available for your account`

Any thoughts about this issue? Thanks.

**Comment by sona-tar** [comment]
👍

**Comment by appleboy** [comment]
I see what is different account type from [LINE official account](https://developers.line.me/type-of-accounts/line-official-account) and [LINE@ account](https://developers.line.me/type-of-accounts/lineat-account) so we need to submit a partnership proposal for a LINE official account with the Business Connect feature.

The default Usable APIs just only `REPLY_MESSAGE `.

![screen shot 2016-11-14 at 9 23 58 am](https://cloud.githubusercontent.com/assets/21979/20250677/4025de64-aa4c-11e6-84bd-53a1ef1feffa.png)

**Comment by sona-tar** [comment]
Developer Trial plan is free access for push message API. But I have no idea to change role to Developer Trial.

**Comment by appleboy** [comment]
@sona-tar How could I change account to Developer Trial plan?

**Comment by GuitarSucks** [comment]
@appleboy
Which country are you based on?
The plans are different per country also

**Comment by appleboy** [comment]
@GuitarSucks Taiwan.

**Comment by appleboy** [comment]
@GuitarSucks I write the [drone-line](https://github.com/appleboy/drone-line) plugin to send build status to user. The new line api version is limited. It is working for previous api version.

**Comment by GuitarSucks** [comment]
OK
For Developer Trial you cant  use the current account. You need to create a new account with Developer Trial.
If you are thinking to make a service you can use PRO plan for push message.
Please check plans here
https://business.line.me/en/services/bot

**Comment by appleboy** [comment]
@GuitarSucks It is working now. I delete my previous account and create new trial account.

![screen shot 2016-11-14 at 10 25 49 am](https://cloud.githubusercontent.com/assets/21979/20251532/c75faa6a-aa54-11e6-8395-0e4d3e395824.png)

**Tip: you must click "Start using Developer Trial" not right button as below.**

![screen shot 2016-11-14 at 10 27 05 am](https://cloud.githubusercontent.com/assets/21979/20251593/63decd1c-aa55-11e6-9c61-2659f53dc0df.png)

Thanks @sona-tar and @GuitarSucks
