### ISSUE TITLE
Refusing to allow a Personal Access Token to create or update workflow

### ISSUE THREAD

**Issue by 1046102779** [line/line-bot-sdk-go#334]
![image](https://user-images.githubusercontent.com/20457624/207226939-3c207938-cc32-4195-8310-570824c5cb53.png)

![image](https://user-images.githubusercontent.com/20457624/207226882-d3a35186-145a-4f01-932c-4fd86328f670.png)

Reasons for changing golang version:

https://github.com/line/line-bot-sdk-go/actions/runs/3682070924/jobs/6229371356

```shell
# github.com/stretchr/testify/assert
Error: ../../../go/pkg/mod/github.com/stretchr/testify@v1.8.1/assert/assertions.go:1798:5: undefined: errors.Is
Error: ../../../go/pkg/mod/github.com/stretchr/testify@v1.8.1/assert/assertions.go:1821:6: undefined: errors.Is
Error: ../../../go/pkg/mod/github.com/stretchr/testify@v1.8.1/assert/assertions.go:[18](https://github.com/line/line-bot-sdk-go/actions/runs/3682070924/jobs/6229371356#step:5:19)44:5: undefined: errors.As
Error: ../../../go/pkg/mod/github.com/stretchr/testify@v1.8.1/assert/assertions.go:1861:7: undefined: errors.Unwrap
Error: ../../../go/pkg/mod/github.com/stretchr/testify@v1.8.1/assert/assertions.go:1865:7: undefined: errors.Unwrap
FAIL	github.com/line/line-bot-sdk-go/v7/linebot [build failed]
note: module requires Go 1.13
Error: Process completed with exit code 1.
```

cc @sugyan @kkdai @clsung.

**Comment by kkdai** [comment]
Hi @1046102779 
Would you please provide a PR for this? Thank you.

**Comment by 1046102779** [comment]
> Hi @1046102779 Would you please provide a PR for this? Thank you.

```shell
To https://github.com/1046102779/line-bot-sdk-go.git
 ! [remote rejected] workflow/upgrade-go -> workflow/upgrade-go (refusing to allow a Pers
onal Access Token to create or update workflow `.github/workflows/go.yml` without `workfl
ow` scope)
error: 推送一些引用到 'https://github.com/1046102779/line-bot-sdk-go.git' 失败
```

I hasn't permission to commit PR in workflow scope.

**Comment by kkdai** [comment]
@1046102779 
It works well in this PR, could you check again? https://github.com/line/line-bot-sdk-go/actions/runs/3682332524

**Comment by 1046102779** [comment]
> @1046102779 It works well in this PR, could you check again? https://github.com/line/line-bot-sdk-go/actions/runs/3682332524

Because I am removing the unit test package(`github.com/stretchr/testify@v1.8.1`) in this PR.  the `testify` package is very popular. 

I think the unit test in the current `line` go-sdk is not well written, you can replace it with the assert package.
