### ISSUE TITLE
Verify channel access token method

### ISSUE THREAD

**Issue by blackhun11** [line/line-bot-sdk-go#337]
Hi line team, i just see that this package doesn't support this endpoint `GET https://api.line.me/oauth2/v2/verify`. Any plan to support this endpoint? thank you

**Comment by blackhun11** [comment]
is it ok if i'm contribute for this api @kkdai ?

**Comment by kkdai** [comment]
@blackhun11 Sure, welcome. :)

**Comment by blackhun11** [comment]
hi @kkdai, can you review my pr? thank you

**Comment by blackhun11** [comment]
hi @kkdai , thank you for merging my pr. since it was merged, can we up the version for release? thank you

**Comment by kkdai** [comment]
Sure, wait a sec.

**Comment by kkdai** [comment]
Fixed by #338 release in v7.19.0
Let me know if you have any questions.
