### ISSUE TITLE
How to set "Imagemap message" image files？

### ISSUE THREAD

**Issue by synr** [line/line-bot-sdk-go#34]
Hello! I read "https://github.com/line/line-bot-sdk-go/blob/master/examples/kitchensink/server.go"
has
```
			linebot.NewImagemapMessage(
				app.appBaseURL+"/static/rich",
				"Imagemap alt text",
				linebot.ImagemapBaseSize{1040, 1040},
				linebot.NewURIImagemapAction("https://store.line.me/family/manga/en", linebot.ImagemapArea{0, 0, 520, 520}),
				linebot.NewURIImagemapAction("https://store.line.me/family/music/en", linebot.ImagemapArea{520, 0, 520, 520}),
				linebot.NewURIImagemapAction("https://store.line.me/family/play/en", linebot.ImagemapArea{0, 520, 520, 520}),
				linebot.NewMessageImagemapAction("URANAI!", linebot.ImagemapArea{520, 520, 520, 520}),
			),
```

I know ``app.appBaseURL+"/static/rich"`` is JPG or PNG file path.
But how can I use ? filename set ``index.jpg`` in  ``app.appBaseURL+"/static/rich"`` path???
or any file name?
or ``app.appBaseURL+"/static/rich/xxx"`` (xxx is int)
or ?????

**Comment by sugyan** [comment]
Details about `baseURL` are written in the document, so please read it.
https://devdocs.line.me/en/#base-url

**Comment by synr** [comment]
I read that.
But I still don't know.
What picture filename set ???

```
https://example.com/images/cats
https://example.com/images/cats/700
```

Any filename is ok?

```
https://example.com/images/cats/123456789.jpg
https://example.com/images/cats/700/123456789.jpg
```

**Comment by mokejp** [comment]
@synr 
I guess you think `700` is a directory name.
`1040`, `700`, `460`, `300` and `240` are filenames, not directory names.
So, you should place images that named 1040, 700 and etc. without extension.

**Comment by synr** [comment]
Thank you!!
I try it and success!

**Comment by uopeydel** [comment]
hey guy i dont understand it to but when i read all comment in this page it still not understand.
please explain me to use image map a little..

https://example.com/images/cats/700.jpg

ex. if i habe image same this how can i do? in image map json? i paste url with no .jpg?  or i will rename it  remove .jpg? or else?
i can set baseUrl = "https://example.com/images/cats/700"
and linkUri ="https://www.google.co.th/"
or other thing?

**Comment by sugyan** [comment]
@uopeydel If you have image file named `700.jpg` and supply as static file, you should copy and resize it and deploy each size.
700.jpg ➡️  (resize to `240x240`) ➡️  `https://example.com/images/cats/240` (no extension)
700.jpg ➡️ (resize to `300x300`) ➡️ `https://example.com/images/cats/300` (no extension)
700.jpg ➡️ (resize to `460x460`) ➡️ `https://example.com/images/cats/460` (no extension)
700.jpg ➡️ (rename) ➡️ `https://example.com/images/cats/700` (no extension)
700.jpg ➡️ (resize to `1040x1040`) ➡️ `https://example.com/images/cats/1040` (no extension)

and you specify `baseUrl` as `https://example.com/images/cats`, it will work well.

**Comment by uopeydel** [comment]
my image is https://xxx.web.com/Content/image/show/700.jpg
its size 460x460
linkUri ="https://xxx.web.com/Content/image/show/460";
baseUrl  ="https://xxx.web.com/Content/image/show";

doesn't work.

**Comment by sugyan** [comment]
@uopeydel 
When you specified `baseUrl` as `https://dev-chat.on.lk/Content/image/show`, LINE client will get image of following URLs

- https://dev-chat.on.lk/Content/image/show/240
- https://dev-chat.on.lk/Content/image/show/300
- https://dev-chat.on.lk/Content/image/show/460
- https://dev-chat.on.lk/Content/image/show/700
- https://dev-chat.on.lk/Content/image/show/1040

so please deploy each size images for them.

Since `linkUri` is for actions, it does not matter.

**Comment by uopeydel** [comment]
yeah i do same you explain its still doesnt work :'(  have you have some example link image can use and work? I think trouble its because my link` https://dev-chat.on.lk/Content/image/show/700.jpg`


this my code.
                  ```
  dynamic area1 = new ExpandoObject();
                    area1.x = 0;
                    area1.y = 0; 
                    area1.width = 460;
                    area1.height = 460;

                    dynamic action1 = new ExpandoObject();
                    action1.type = "uri";
                    action1.linkUri = "https://dev-chat.on.lk/Content/image/show/460";
                    action1.area = area1;

                   dynamic baseSized = new ExpandoObject();
                    baseSized.height = 460;
                    baseSized.width = 460;


                    dynamic Imagemap = new ExpandoObject();
                    Imagemap.type = "imagemap";
                    Imagemap.baseUrl = "https://dev-chat.on.lk/Content/image/show";
                    Imagemap.altText = "this is an imagemap";
                    Imagemap.baseSize = baseSized;
                    Imagemap.actions = new List<ExpandoObject>();
                    Imagemap.actions.Add(action1);
```

**Comment by sugyan** [comment]
@uopeydel 
I've wrote URLs which must return image.

https://dev-chat.on.lk/Content/image/show/240
https://dev-chat.on.lk/Content/image/show/300
https://dev-chat.on.lk/Content/image/show/460
https://dev-chat.on.lk/Content/image/show/700
https://dev-chat.on.lk/Content/image/show/1040

but they still return "404 Not Found". Please upload each size images...

**Comment by uopeydel** [comment]
https://dev-chat.on.lk/Content/image/show/700.jpg  <<  but this link can do image ?

**Comment by sugyan** [comment]
@uopeydel 
No. No. URL is https://dev-chat.on.lk/Content/image/show/700. There is no extension like ".jpg".

Files of example app https://github.com/line/line-bot-sdk-go/tree/master/examples/kitchensink/static/rich have no extensions, but static server returns image content. You must supply image in https://dev-chat.on.lk/Content/image/show/700, not https://dev-chat.on.lk/Content/image/show/700.jpg.

**Comment by uopeydel** [comment]
ok i understand , have some guid for create file like that? give me some key word for search. i nerver do that ._.

**Comment by highmusahi** [comment]
"type": "imagemap",                  "baseUrl":"http://res.cloudinary.com/dazmnrals/image/upload/v1498200198/honda_car/brio/240",
                    "altText": "this is an imagemap",
                    "baseSize": {
                         "height": 240,
                         "width": 240
                    },
                    "actions": [
                      {
                          "type": "uri",
                          "linkUri": "http://res.cloudinary.com",
                          "area": {
                              "x": 0,
                              "y": 0,
                              "width": 240,
                              "height": 240
                          }
                      }
i try this but it doesn't work at all
doc: https://devdocs.line.me/en/#imagemap-message

**Comment by jaajaah** [comment]
@sugyan 
thanks  when i upload 5 file size and i can do it success,
but i want to upload image 1 file only ,Can i do ?

**Comment by StefanMao** [comment]
where imagemap you want to set?

2017年7月3日 12:44，"jaajaah" <notifications@github.com>寫道：

**Comment by StefanMao** [comment]
sorry I'm in China travel
I don't really understand your problem.
pls clearly ask you problem

2017年6月23日 18:08，"highmusahi" <notifications@github.com>寫道：

**Comment by jaajaah** [comment]
@StefanMao
thanks ,, I tested upload 5 files it's work. 
But I want to upload just 1 file  
What should I do ? Can you suggest me please ?

**Comment by IT5706021631069** [comment]
@jaajaah 
Can you show your code about image map?
Thanks.

**Comment by IT5706021631069** [comment]
i upload 5 size images on github(https://github.com/IT5706021631069/imagemap_line/tree/master/rich/)
but it show Unable to load image.

**Comment by jaajaah** [comment]
@IT5706021631069 
{
  "type": "imagemap",
  "baseUrl": "https://example.com/images/pic001",
  "altText": "this is an imagemap",
  "baseSize": {
    "height": 1040,
    "width": 1040
  },
  "actions": [
    {
      "type": "uri",
      "linkUri": "https://example.com/",
      "area": {
        "x": 0,
        "y": 0,
        "width": 520,
        "height": 1040
      }
    }
  ]
}

//***************************************
directory for upload 5 file  no extensions
..//images/pic001/240
..//images/pic001/300
..//images/pic001/460
..//images/pic001/700
..//images/pic001/1040
