### ISSUE TITLE
Add UnmarshalJSON method to Template

### ISSUE THREAD

**Issue by yoshinobc** [line/line-bot-sdk-go#345]
Thank you for all your development.
While I was using `line-bot-sdk-go`, I noticed that the `UnmarshalJSON` method exists for `FlexMessage`, but not for `TemplateMessage`.
Therefore, I could not save `TemplateMessage` as a json file.
In the other line-bot-sdk(e.g. [line-bot-sdk-python](https://github.com/line/line-bot-sdk-python)), the `UnmarshalJSON` method exists in `TemplateMessage` as well, so I don't think this is an unwanted feature.

Please check the PR I have created to add `UnmarshalJSON` to `TemplateMessage`.

**Comment by Yang-33** [comment]
closed by https://github.com/line/line-bot-sdk-go/pull/346
