### ISSUE TITLE
[Feature Suggestion] Would you have a plan to refresh access_token automatically?

### ISSUE THREAD

**Issue by MarkRunWu** [line/line-bot-sdk-go#35]
Because you have a [reissuing-access-tokens](https://devdocs.line.me/en/#reissuing-access-tokens) API for this, I just wonder if you have a plan to let robot can refresh access token by itself before the token is expired.

**Comment by sugyan** [comment]
Sorry, token's refresh is mandatory for security reasons.
Thank you.
