### ISSUE TITLE
Missing STKVER from webhooks event in API v2

### ISSUE THREAD

**Issue by gigapixel** [line/line-bot-sdk-go#42]
In bot API v1 we can get following sticker info.
`
{
 ...
  "STKVER": "100",
  "STKID": "1",
  "STKPKGID": "1"  
}
`

But in v2 it only has `stickerId` and `packageId` from webhooks event.
`
{
  ...
  "packageId": "1",
  "stickerId": "1"
}
`

Could you please tell me how to get the version of sticker sent by user?

**Comment by tokuhirom** [comment]
Why do  you want a stkver? We removed it since it's not required.

**Comment by gigapixel** [comment]
My app has feature to preview sticker sent from user, in v1 we have used those 3 fields to get sticker url for preview.

If it's not required in v2, please tell me how to preview sticker sent from user in v2?

**Comment by tokuhirom** [comment]
Close this issue at this moment. If you still need help, please reopen this issue.
