### ISSUE TITLE
Enable to create Messaging API channel in developer console

### ISSUE THREAD

**Issue by rukavina** [line/line-bot-sdk-go#454]
![Screenshot from 2024-06-07 10-53-10](https://github.com/line/line-bot-sdk-go/assets/881367/47dbbcc6-9f78-42df-a278-e326f91f9bec)

The create Messaging API channel is disabled, no official explanation for that exists.

Is there any particular reason, like line account country restriction?

Thanks

**Comment by Yang-33** [comment]
I'm unfamiliar with that, but I guess you don't have enough permission. https://developers.line.biz/en/docs/line-developers-console/managing-roles/#roles-for-provider

and this repository is only for line-bot-sdk-go, sorry we can't support you here... :pray:

**Comment by rukavina** [comment]
Thanks!
I managed to make a channel the other way around, by creating the official account and then assigning it to the provider. I still don't get it why the regular way is disabled, all permissions are there, but anyway outcome is the same.

Thanks again
