### ISSUE TITLE
Webhook on localhost

### ISSUE THREAD

**Issue by monopollly** [line/line-bot-sdk-go#46]
Yep I read that I can't use SDK on localhost... but how is possible to develop something without testing? Develop on a production server?
I really don't understand...

Whats the best practice to do a good bot without it?
Thanks!

**Comment by StefanMao** [comment]
mu ...
I use gitbash and cmd line to debug

code and save , cmd line  to upload your new code to Heroku and debug



2017年7月1日 05:44，"Piu Piu" <notifications@github.com>寫道：

**Comment by krrrr38** [comment]
@monopollly how about to use [ngrok](https://ngrok.com/)?
like https://developer.github.com/webhooks/configuring/, you can set webhook url such as `http://blahblah.ngrok.io/payload`.

**Comment by krrrr38** [comment]
and this issue is not related to sdk go. please create faq issue to https://github.com/line/line-bot-faq :)
