### ISSUE TITLE
I would like to see QuotedMessageID added.

### ISSUE THREAD

**Issue by MocA-Love** [line/line-bot-sdk-go#489]
### message.go
```go
type TextMessage struct {
	ID     string
	Text   string
	Emojis []*Emoji

	quickReplyItems *QuickReplyItems
	sender          *Sender
	messageType     MessageType

	Mention *Mention
}

```

maybe ... QuotedMessageID string `json:"quotedMessageId,omitempty"` ?

**Comment by habara-k** [comment]
Thank you for using the Messaging API and line-bot-sdk-go.

We appreciate your feedback. However, as stated at https://github.com/line/line-bot-sdk-go/blob/d8c5a4d23eec8e4fd1b882574882d4a6edee9b16/linebot/event.go#L256-L257, the `rawEventMessage` is deprecated, and we will not be providing further support for it. 
We appreciate your understanding.

**Comment by habara-k** [comment]
Thank you for using the Messaging API and line-bot-sdk-go.

We appreciate your feedback. However, as stated at https://github.com/line/line-bot-sdk-go/blob/master/linebot/message.go#L53-L54, the `rawEventMessage` is deprecated, and we will not be providing further support for it. 
We appreciate your understanding.
