### ISSUE TITLE
Timeline for dropping Go 1.6?

### ISSUE THREAD

**Issue by m90** [line/line-bot-sdk-go#58]
The `linebot` package currently pulls in 3rd party `context` and `ctxhttp` as its only dependencies.

Those are part of the standard library as of Go 1.7. Almost all packages follow the pattern of supporting current and last releases of Go, so this is currently supporting many more versions than any of my other dependencies.

Are there any plans of moving to standard library context with this SDK? Considering the situation around Go and dependency management I guess it's a good idea to have a dependency less package for others to depend on if possible.

**Comment by tokuhirom** [comment]
Google GAE still not support Go 1.[78]. We can drop Go 1.6 support after GAE support Go 1.8.

**Comment by clsung** [comment]
According to https://cloud.google.com/appengine/docs/go/, GAE should officially support Go 1.8 (default) now.
