### ISSUE TITLE
Would it be an option to change the visibility of the private methods in interfaces that embed json.Marshaler?

### ISSUE THREAD

**Issue by m90** [line/line-bot-sdk-go#59]
I am dealing with the current scenario: I am building a proxy that connects multiple messenger services including LINE to an NLP backend (api.ai in that case). For some messages the backend will send something called "custom payload" which is basically a messenger specific JSON string that could be passed through to the messenger without touching.

When using package `linebot` I will unfortunately have to deparse this Message and construct a new Message (which ends up being the very same) using the supplied methods, which works but is very tedious.

The easiest option would be if I could simply implement interfaces like `Message` myself. This is not possible due to the fact that the library attaches empty, invisible methods like [`message()`](https://github.com/line/line-bot-sdk-go/blob/3a7d66f5efce6ac202f650134609f9d6d163a640/linebot/message.go#L37-L40) or `template()` to these interfaces. The fact that they are lowercased/invisible currently makes it impossible to have anything outside of package `linebot` implement these interfaces.

Is there any reason this is being done? Would you accept a PR (basically consisting of [this commit](https://github.com/m90/line-bot-sdk-go/commit/a26d35002758837115e1202b8e905c9ad223c389)) that changes the visibility of these interface members, thus allowing 3rd parties to implement the libraries interfaces?

**Comment by m90** [comment]
Is there any input on this one? Otherwise it's probably best to close it so I know how I need to proceed.

**Comment by sugyan** [comment]
Sorry for the late reply.
It was implemented as a mechanism for passing safe data types, but as you mention, it may be inconvenient that they are lowercased/invisible.
If you create PR to change visibility, we will accept it :)

**Comment by m90** [comment]
Done so in #71.
