### ISSUE TITLE
When will release new sdk version that having ImageCarouselTemplate, DatetimePickerTemplateAction and other method?

### ISSUE THREAD

**Issue by justdomepaul** [line/line-bot-sdk-go#77]
I use golang/dep to get line-bot-sdk-go package.

My Download version is only 1.0.0, not having new function that having ImageCarouselTemplate, DatetimePickerTemplateAction etc.

Have any way to use latest version on using dep or glide package manager?

**Comment by sugyan** [comment]
Sorry for the late reaction.
I added the 1.1.0 tag to the latest commit.
