### ISSUE TITLE
New LIFF API PR

### ISSUE THREAD

**Issue by justdomepaul** [line/line-bot-sdk-go#89]
my new PR: https://github.com/line/line-bot-sdk-go/pull/83

I PR a latest version, please code review and merge to master.

Please close my Before issue: https://github.com/line/line-bot-sdk-go/issues/84

Thanks.

**Comment by sugyan** [comment]
Thanks for updating your pull-request.
It seems almost good, but I have some comments for improvement.


1. `liff.go` has some problems with comments and field names.

```
linebot/liff.go:26:6: exported type LIFFAPP should have comment or be unexported
linebot/liff.go:31:6: exported type ViewRequest should have comment or be unexported
linebot/liff.go:35:6: exported type View should have comment or be unexported
linebot/liff.go:37:2: struct field Url should be URL
linebot/liff.go:40:1: comment on exported method Client.GetLIFF should be of the form "GetLIFF ..."
linebot/liff.go:71:1: comment on exported method Client.AddLIFF should be of the form "AddLIFF ..."
linebot/liff.go:118:1: comment on exported method Client.UpdateLIFFCall should be of the form "UpdateLIFFCall ..."
linebot/liff.go:119:38: method parameter liffId should be liffID
linebot/liff.go:146:3: struct field Url should be URL
linebot/liff.go:171:1: comment on exported method Client.DeleteLIFFCall should be of the form "DeleteLIFFCall ..."
linebot/liff.go:172:38: method parameter liffId should be liffID
```

please install and run `golint` (golang.org/x/lint/golint) and check outputs.


2. method name has no consistency.
I think `func (client *Client) UpdateLIFFCall` and `func (client *Client) DeleteLIFFCall` should be named `UpdateLIFF` and `DeleteLIFF`, which shouldn't include `Call`.


and...

This pull-request seems to contain many commits unrelated to LIFF.
I'd be happy if you make different pull-request which only include relevant changes as separate branches.

Did you sign the ICLA? https://feedback.line.me/enquete/public/919-h9Yqmr1u
Please submit that if you didn't submit yet.

**Comment by justdomepaul** [comment]
Ok, I will modify these issue, rebase commit and push latest version.

**Comment by justdomepaul** [comment]
https://github.com/line/line-bot-sdk-go/pull/90

I separate a new alone "liff api" branch, golint file, and change func name to your suggestion.

ps. I have applied ICLA recently.
