### ISSUE TITLE
proposal: Use CodeCov

### ISSUE THREAD

**Issue by suzuki-shunsuke** [line/line-bot-sdk-go#93]
CodeCov is SaaS to visualize code coverage, and useful to improve code quality.

Note that the below samples refer my personal repositories.

* About CodeCov: https://docs.codecov.io/docs/about-code-coverage
* Sample status badges: [![codecov](https://codecov.io/gh/suzuki-shunsuke/go-set/branch/master/graph/badge.svg)](https://codecov.io/gh/suzuki-shunsuke/go-set) [![codecov](https://codecov.io/gh/suzuki-shunsuke/go-graylog/branch/master/graph/badge.svg)](https://codecov.io/gh/suzuki-shunsuke/go-graylog)
* Sample pages
  * https://codecov.io/gh/suzuki-shunsuke/go-graylog
  * https://codecov.io/gh/suzuki-shunsuke/go-set
  * https://codecov.io/gh/suzuki-shunsuke/go-graylog/src/master/client/stream_rule.go
* Sample [Pull Request Comments](https://docs.codecov.io/docs/pull-request-comments)
  * https://github.com/suzuki-shunsuke/go-graylog/pull/8#issuecomment-401587635

**Comment by sugyan** [comment]
LGTM 👍
